// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'usb.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `into`, `into`

/// get all usb infos
Future<List<UsbInfo>> getUsbInfos() =>
    RustLib.instance.api.crateApiUsbGetUsbInfos();

@freezed
@meta.immutable
class UsbInfo with _$UsbInfo {
  const factory UsbInfo({
    required int busNumber,
    required int address,
    required int vendorId,
    required int productId,
    required int numConfigurations,
    required int maxPacketSize,
    required int protocolCode,
    required int subClassCode,
    required int classCode,
    int? serialNumberStringIndex,
    int? productStringIndex,
    int? manufacturerStringIndex,
    required UsbVersion usbVersion,
    required UsbVersion deviceVersion,
    required int descriptorType,
    required int length,
  }) = _UsbInfo;
}

@freezed
@meta.immutable
class UsbVersion with _$UsbVersion {
  const factory UsbVersion({
    required int field0,
    required int field1,
    required int field2,
  }) = _UsbVersion;
}
